### ISSUE TITLE
Синтаксическая ошибка в модуле обработки Выгрузка конфигурации

### ISSUE THREAD

**Issue by Gamms** [pumbaEO/v83unpack#17]
Не хватает закрывающего КонецЕсли в строке 1731 
Функция РазложитьМодули1СПоПапкамСогласноИерархииМетаданных

**Comment by pumbaEO** [comment]
Этот проект скорей закрыт и мигрировал сюда https://github.com/EvilBeaver/oscript-library/tree/develop/src/gitsync

**Comment by JohnyDeath** [comment]
@pumbaEO может эту информацию на заглавную страничку выставить?
